### ISSUE TITLE
Moderation

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/pikyak#2]
#1 needs moderation.  Any ideas for how it should work, @KevinOStephens and @ckelso94?

**Comment by ckelso94** [comment]
We could give the users the ability to flag posts and create one account to see and take down these conversations as they see fit.  They would have the same capabilities as a regular user but would also just be able to see and delete flagged posts. They could have like an extra tab at the top called flagged with all of the flagged posts sorted most to least. Maybe auto delete posts at 5 flags.

**Comment by thirtythreeforty** [comment]
Described with 79bcf18; let me know what you think.
