### ISSUE TITLE
Design document

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/pikyak#3]
Guys,
We need to start on this ASAP.  UML class diagrams should be doable in [MetaUML](http://metauml.sourceforge.net/old/class-diagram.html) which looks quite pleasant.  I can handle most of the LaTeX wrangling if you want to use it, but it mainly needs _writing._  Let's hash out the classes and database structure here, then we can boilerplate it into the design doc.

**Comment by thirtythreeforty** [comment]
The client and server can mostly mimic each others' class structure, but obv. if we're using Python for the server, we can't reuse the actual class definitions on the client side.  I'd like these definitions to map directly into the database with [SQLAlchemy](www.sqlalchemy.org) or similar.  Here's a User class for the server.  Feel free to edit this.

> ## User
> 
> -string email
> -string password (hashed)
> -bool isModerator
> -bool passwordIsReset
> 
> ---
> 
> +User(email, password)
> +checkPassword(plaintext): bool
> +isPasswordReset(): bool

**Comment by KevinOStephens** [comment]
```
User

-string email
-string password (hashed)
-bool isModerator
-bool passwordIsReset
-score

+User(email, password)
+checkPassword(plaintext): bool
+isPasswordReset(): bool
+getScore(): int
```

**Comment by thirtythreeforty** [comment]
Why does the User need a score?  That's reserved for individual posts I thought.

Regarding scores, we would need a way to keep track of whether the user has voted on any given post.  I think the best way to do this is to have a Vote class (with a corresponding db table) with a pointer to the User and a pointer to the Post in question.

Regarding posts.  I think it would be good to have a Post class and a Conversation class.  That way, it is easier to do things like send a push notification when a reference to the existing Conversation is added to the database.  Each Post would reference exactly one Conversation, and we could fetch a Conversation for the client by just looking for all the Posts referencing it.

I'm not sure of the best way to score Conversations yet.  Should it be the score of the original Post made to it?  If so, that should be fairly simple and cheap.  If we do something like sum the scores of the original Post and all the replies, that's going to be a more expensive DB call (although still doable).

Thoughts?

**Comment by ckelso94** [comment]
I think they way they do it on yik yak is that a conversation score is literally calculated just upvotes-downvotes.  Replies don't count.

**Comment by thirtythreeforty** [comment]
Sounds good.  Anyone want to make UML for the other classes?  I think I can copy/paste them into LaTeX and get all the diagrams looking nice, but can you guys handle most of the text that needs to be written?

**Comment by ckelso94** [comment]
I will later tonight or in the morning.

**Comment by ckelso94** [comment]
Post
-postId:int
-data:String\* //ptr to the picture
-isReply:bool
+Post(postID, data):void

Conversation
-conID:int
-numPost:int
-score:int
+conversation(conID, Post):void
+reply(Post):void

Vote
-user:User*
-post:Post*

We need the flags in there also, are we flagging posts or conversations?
Also, do individual posts have scores or just conversation as a whole?

**Comment by KevinOStephens** [comment]
If we are doing this exactly like yikyak; everything has a score.  So, both individual posts and conversations need scores.

**Comment by ckelso94** [comment]
**Image**
-data:string*
+Image(data)

**Post**
-postId:int
-data:Image
-isFirst:bool
-date:string
-flagCount:int
-score:int
+Post(postID, data):void
+postDisplay():void
+flagPost():void
+deletePost():void

**Conversation**
-conID:int
-numPost:int
+conversation(conID, Post):void
+addReply(Post):void
+conDisplay():void
+deleteConversation():void

**Vote**
-user:User*
-post:Post*

**User**
-email:string
-password:string
-isModerator:bool
-isRegistered:bool
-passwordIsReset:bool
+User():void
+User(email, password):void
+checkPassword(plaintext):bool
+isPasswordReset():bool

**Comment by ckelso94** [comment]
changed some of that a little bit.  Just committed it. Just need someone to look over it and put it in latex format

**Comment by thirtythreeforty** [comment]
Alright.  I'll have it in LaTeX shortly.

**Comment by KevinOStephens** [comment]
Is this in a UML diagram yet?

**Comment by thirtythreeforty** [comment]
It is now!  As of fba44a8, [here's what it looks like](https://pdf.yt/d/8KftKrPkoDhmwuBH/download).
