### ISSUE TITLE
Flagging

### ISSUE THREAD

**Issue by ckelso94** [thirtythreeforty/pikyak#6]
Need to implement flags in our design.  Omitted them from our presentation.

**Comment by thirtythreeforty** [comment]
This will require a new Flag class which is similar to the Vote class.
Going forward, this may also require a Deleted attribute on the Post/Conversation.  How should we handle if the original Post is deemed offensive?  Should the entire Conversation be removed?

**Comment by ckelso94** [comment]
I think we should just flag individual posts.  If the post is the first in the conversation, delete the whole conversation.  Otherwise just remove that post.

**Comment by thirtythreeforty** [comment]
Sounds good.  One thing we may want to implement if we have time is shadowbanning, which removes the content for everyone except the content owner, so they can't tell they've been muted.
