### ISSUE TITLE
Finish API

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/pikyak#7]
The API needs:
- [ ] posting
- [ ] voting
- [ ] moderation

Doesn't have to be entirely implemented, just defined.  Don't forget to specify where the `Authentication` header is needed.

**Comment by thirtythreeforty** [comment]
I've assigned @ckelso94 but I guess both you and @KevinOStephens need to talk about this together.

**Comment by thirtythreeforty** [comment]
I [modified](https://github.com/thirtythreeforty/pikyak/wiki/API/_compare/7e7615e9c15d630843d3fdce1a2f4a5da8d76684...ee08d8f54007ce8c565b5e7fdebc370c73792a29) the [API](https://github.com/thirtythreeforty/pikyak/wiki/API) a bit.  Should make it easier to implement on your end; let me know.  I know it simplifies the client a lot.

**Comment by ckelso94** [comment]
Thanks. Going to work on it later today. Let me know what you think
